;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				c-electric-delete-forward
				c-electric-paren
				c-electric-semi&comma
				c-electric-star
				find-file
				indent-for-tab-command
				mark-sexp
				org-yank
				wdired--self-insert
				))

(setq mc/cmds-to-run-once
      '(
				ace-window-golden-ratio
				consult-buffer
				recompile
				))
